// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ExploreShowView: typeof import('./src/components/ExploreShowView.vue')['default']
    FinishRegisterView: typeof import('./src/components/FinishRegisterView.vue')['default']
    MyRecordChildrenView: typeof import('./src/components/MyRecordChildrenView.vue')['default']
    MySettingView: typeof import('./src/components/MySettingView.vue')['default']
    RegisterPageView: typeof import('./src/components/RegisterPageView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanDatetimePicker: typeof import('vant/es')['DatetimePicker']
    VanLoading: typeof import('vant/es')['Loading']
    VanShareSheet: typeof import('vant/es')['ShareSheet']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
